[OAUTHSNOW]
account = "BQQXJER-FVB74418"
authorization_endpoint = "https://eub73820.us-east-1.snowflakecomputing.com/oauth/authorize"
token_endpoint = "https://eub73820.us-east-1.snowflakecomputing.com/oauth/token-request"
redirect_uri = "http://localhost:8501"
client_id = "F8QcrSpBLOIjjUwTBRUMWpq0myY="
client_secret = "Yv1SP6A+R20makruZ4AwQQ75D4Zj/cuB3tvU8SrPyCo="
role = "CLIENTES_CONSUMIDORES"

